//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIUB_Forum.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobId { get; set; }
        public int CompanyId { get; set; }
        public string JobType { get; set; }
        public string PositonName { get; set; }
        public string Description { get; set; }
        public string Salary { get; set; }
        public string Loaction { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
